# docker-compose --compatibility up -d --build
# docker-compose down

version: "3.1"
services:
  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: diesel_demo
    volumes:
      ### ホスト:コンテナ 
      - ./data:/var/tmp
